### ISSUE TITLE
Pls Bring Zeta Online

### ISSUE THREAD

**Issue by Goldenfreddy0703** [NateM135/zeta#1]
HI, Zeta has been helping me in my server a lot especially with Color-chan because Color-chan needs premium to delete messages sadly which is why i use Zeta alot. Is there anyway you guys can bring Zeta back online and can i have an invite to your support server sense the one on the website is not working? It would really mean alot and thank you.

**Comment by n4t3m** [comment]
Hello, here is the support server link: https://discord.gg/4e25RDd

Somehow the bot went down but I have no idea why. I'm investigating now. The bot is now back online.

If possible, can you link me where you got the broken support server link?

Thanks again for using the bot and sorry for the downtime.

**Comment by Goldenfreddy0703** [comment]
Thank youuuuu. :D
